apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 'external-secrets-operator'
  namespace: flux-system
spec:
  chart:
    spec:
      chart: 'external-secrets'
      interval: 1m0s
      reconcileStrategy: 'ChartVersion'
      sourceRef:
        kind: 'HelmRepository'
        name: 'external-secrets-operator'
        namespace: 'flux-system'
      version: '0.9.2'
  interval: 1m0s
  targetNamespace: 'external-secrets-operator'
