apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 'cert-manager'
  namespace: flux-system
spec:
  chart:
    spec:
      chart: 'cert-manager'
      interval: 1m0s
      reconcileStrategy: 'ChartVersion'
      sourceRef:
        kind: 'HelmRepository'
        name: 'cert-manager'
        namespace: 'flux-system'
      version: '1.9.1'
  interval: 1m0s
  targetNamespace: 'cert-manager'
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-config
