apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/part-of: cert-manager
  name: letsencrypt-production
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: production
    solvers:
      - selector:
          dnsZones:
            - "{{ .Values.domain }}"
        dns01: 
          route53:
            hostedZoneID: {{ .Values.hosted_zone_id }}
            region: {{ .Values.region }}
            accessKeyID: {{ .Values.iam_credentials.access_key_id }}
            secretAccessKeySecretRef:
              name: {{ .Values.iam_credentials.secret_access_key.secret_name }}
              key: {{ .Values.iam_credentials.secret_access_key.secret_key }}