apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: istio-system
spec:
  dnsNames:
    - "vault.{{.Values.domain}}"
  issuerRef: 
    name: {{ .Values.issuer }}
    kind: ClusterIssuer
  secretName: vault-tls