apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "{{ .Values.vaultURL }}"
      path: "{{ .Values.secretsPath }}"
      version: "{{ .Values.secretEngineVersion }}"
      auth:
        tokenSecretRef:
          name: "{{ .Values.esoPolicyTokenSecret }}" 
          key: "{{ .Values.esoPolicyTokenSecretKey }}" 
          namespace: "{{ .Values.esoPolicyTokenSecretNamespace }}" 