apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: certificate
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cluster/add-ons/cert-manager/chart
      interval: 10m0s
      sourceRef:
        kind: GitRepository
        name: add-ons
        namespace: flux-system
  interval: 10m0s
  targetNamespace: cert-manager
  dependsOn:
    - name: cert-manager
      namespace: flux-system
    - name: bigbang
      namespace: bigbang
  valuesFrom:
    - kind: ConfigMap
      name: certificate-config
    - kind: ConfigMap
      name: tf-certificate-config
