apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-add-on
  namespace: flux-system
spec:
  dependsOn:
    - name: bigbang-add-on
  interval: 10m0s
  path: /cluster/add-ons/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: add-ons
