apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - manifests/sync.yaml
  - manifests/cert-manager/helmrelease.yaml
  - manifests/cert-manager/helmrepository.yaml
  - manifests/cert-manager/ns.yaml
  - manifests/certificate/helmrelease.yaml

configMapGenerator:
  - name: cert-manager-config
    namespace: flux-system
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=manifests/cert-manager/values.yaml
  - name: certificate-config
    namespace: flux-system
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=manifests/certificate/values.yaml