apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - manifests/sync.yaml
  - manifests/external-secrets/helmrelease.yaml
  - manifests/external-secrets/helmrepository.yaml
  - manifests/external-secrets/namespace.yaml
  - manifests/eso-config/helmrelease.yaml

configMapGenerator:
  - name: eso-config
    namespace: flux-system
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=manifests/eso-config/values.yaml