apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eso-config
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cluster/add-ons/external-secrets/chart
      interval: 10m0s
      sourceRef:
        kind: GitRepository
        name: add-ons
        namespace: flux-system
  interval: 10m0s
  targetNamespace: default
  valuesFrom:
    - kind: ConfigMap
      name: eso-config
  dependsOn:
    - name: external-secrets-operator
      namespace: flux-system
    - name: vault
      namespace: bigbang
