apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - https://repo1.dso.mil/big-bang/bigbang//base?ref=2.9.0
  - sync.yaml

configMapGenerator:
  - name: common
    behavior: merge
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=values.yaml