apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: aws-ccm-add-on
  namespace: flux-system
spec:
  interval: 10m0s
  path: /cluster/add-ons/aws-ccm
  prune: true
  sourceRef:
    kind: GitRepository
    name: add-ons